name: Windows
on: [push, pull_request, workflow_dispatch]
jobs:
  WindowsRun:
    runs-on: windows-2019
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.4
        id: cuda-toolkit
        with:
          cuda: '11.2.2'  
          linux-local-args: '["--toolkit"]'
      - run: nvcc -V      
      - name: Checkout
        uses: actions/checkout@v2            
      - name: Create build directory
        run: mkdir ${{github.workspace}}/build      
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../
      - name: Run VS
        run: cmake --build ${{github.workspace}}/build --clean-first --config Release -j 4
      #- name: Run Test
      #  working-directory: ${{github.workspace}}/build
      #  run: ctest --no-compress-output -T Test -C Release --output-on-failure
      - run: echo "This job's status is ${{ job.status }}."
